# Generated by Django 4.2.1 on 2023-05-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='serie',
            field=models.CharField(max_length=1),
        ),
    ]
